const DUMMYDATA = [
  {
    title: '제목1',
    content: 'I have done some analysis and have decided to provide the search for DB search for full text for mysql db How to integrate elastic search and handle the delta happens in mysql -',
    tags: ['태그', '태그태그', '태그태그태그'],
    userName: '유저1',
    askCount: '234',
    userTime: '54',
    votes: '3',
    answers: '9',
    views: '23',
  },
  {
    title: '제목2',
    content: 'the search for DB search for full text for mysql db How to integrate elastic search and handle the delta happens in mysql -',
    tags: ['태그태그태그', '태그태그', '태그'],
    userName: '유저2',
    askCount: '876',
    userTime: '23',
    votes: '42',
    answers: '76',
    views: '1',
  },
  {
    title: '제목3',
    content: 'me analysis and have decidrch for full text for mysql db How to integrate elastic search and handle the delta happens in mysql -',
    tags: ['태그', '태그태그태그', '태그태그'],
    userName: '유저3',
    askCount: '23',
    userTime: '35',
    votes: '76',
    answers: '2',
    views: '54',
  },
  {
    title: '제목4',
    content: 'haveome analysis and have decided to provide the search for DB search for fuysql db How to integrate elastic search and handle the delta happens in mysql -',
    tags: ['태그', '태그태그태그태그', '태그태그태그태그'],
    userName: '유저4',
    askCount: '785',
    userTime: '1',
    votes: '32',
    answers: '11',
    views: '29',
  },
  {
    title: '제목5',
    content: 'for full text for mysql db How to integrate elastic search and handle the delta happens in mysql -',
    tags: ['태그태그태그태그', '태그태그', '태그태그태그태그태그태그태그'],
    userName: '유저5',
    askCount: '42',
    userTime: '5',
    votes: '25',
    answers: '32',
    views: '88',
  },

];

export default DUMMYDATA;
